import Head from 'next/head'
import Sidebar from '../Components/Sidebar'
import Feed from '../Components/Feed'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
        <main className={"flex min-h-screen max-w-7xl mx-auto"}>
        {/* Sidebar */}
        <Sidebar />
        {/* Feed */}
        <Feed/>
        {/* Widgets */}

        {/* Modal */}
        </main>
    </div>
  )
}
